package org.rabix.bindings.cwl1.bean.resource;

public enum Draft3ResourceType {

  AWS_INSTANCE_TYPE,
  FORCE_GOOGLE_INSTANCE,
  DOCKER_RESOURCE,
  INLINE_JAVASCRIPT_REQUIREMENT,
  SHELL_COMMAND_REQUIREMENT,
  RESOURCE_REQUIREMENT,
  CREATE_FILE_REQUIREMENT,
  SCHEMA_DEF_REQUIREMENT,
  ENV_VAR_REQUIREMENT,
  OTHER
}
