package org.rabix.bindings.sb.bean.resource;

public enum SBResourceType {

  AWS_INSTANCE_TYPE,
  FORCE_GOOGLE_INSTANCE,
  CPU_RESOURCE,
  MEMORY_RESOURCE,
  DOCKER_RESOURCE,
  EXPRESSION_ENGINE_REQUIREMENT,
  IO_REQUIREMENT,
  CREATE_FILE_REQUIREMENT,
  SCHEMA_DEF_REQUIREMENT,
  ENV_VAR_REQUIREMENT,
  OTHER
}
